### ISSUE TITLE
ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by coxato** [danielfrg/demucs-service#1]
Hi Daniel, I saw you made wordle in Spanish I really liked it. So I was checking this project demucs just for fun because I think is awesome to separate a song in different instruments, so I tried to upload the test mp3 file but I see this:
![image](https://i.ibb.co/M7gkbCq/img.png) 

it says ERR_CONNECTION_CLOSED maybe is something with the server, probably add seconds to the timeout, btw my internet is very slow so maybe that's also a problem. 

Anyway I like the idea and I like wordle, have a good day :)

**Comment by danielfrg** [comment]
The service is down at the moment because it was getting expensive, I will try to find a solution for that when i have the time

**Comment by garvord** [comment]
> The service is down at the moment because it was getting expensive, I will try to find a solution for that when i have the time

Hi Daniel,

Tried your service and get a "fetch error: Failed to fetch". 
May I assume the service is still down, or is this a different issue?
I Can provide more info if this is a real issue.

Have a great day!

**Comment by inwardmovement** [comment]
Having the `Failed to fetch` issue too
